name: myapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.16.0
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  flutter_easyloading: ^2.2.2
  flutter_hooks: ^0.15.0
  flutter_state_notifier: ^0.6.1
  freezed_annotation: ^0.12.0
  github_sign_in: ^0.0.3
  hooks_riverpod: ^0.12.4
  json_annotation: ^3.1.1
  logger: ^0.9.4
  pretty_dio_logger: ^1.1.1
  provider: ^4.3.3
  retrofit: ^1.3.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  freezed: ^0.12.7
  json_serializable: ^3.5.1
  retrofit_generator: ^1.4.1+2

flutter:
  uses-material-design: true

  assets:
    - images/
