name: myapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.16.0
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  flutter_dotenv: ^3.1.0
  flutter_easyloading: ^3.0.0
  flutter_hooks: ^0.16.0
  flutter_state_notifier: ^0.7.0
  freezed_annotation: ^0.14.1
  github_sign_in: ^0.0.3
  hooks_riverpod: ^0.13.1+1
  image_picker: ^0.6.7+22
  json_annotation: ^4.0.0
  logger: ^1.0.0
  pretty_dio_logger: ^1.1.1
  retrofit: ^1.3.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  freezed: ^0.14.1
  retrofit_generator: ^1.4.1+3

flutter:
  uses-material-design: true

  assets:
    - .env
    - images/
